language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - build-tools-24.0.3
    - android-25
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.*'

branches:
  only:
    - test/travis-ci

script: ./gradlew build

jdk:
  - oraclejdk8
