language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.2
    - build-tools-25.0.0
    - android-24

script:
   - ./gradlew build

jdk:
  - oraclejdk8
