package dateadog.dateadog.schemaobjects.types;

public enum DogType implements IBreedType {
	// DOG BREEDS
    	HINT("Breed (Optional)", ""), 
	AFFENPINSCHER("Affenpinscher", "Affenpinscher"),
	AFGHAN_HOUND("Afghan Hound", "Afghan%20Hound"),
	AIREDALE_TERRIER("Airedale Terrier", "Airedale%20Terrier"),
	AKBASH("Akbash", "Akbash"),
	AKITA("Akita", "Akita"),
	ALASKAN_MALAMUTE("Alaskan Malamute", "Alaskan%20Malamute"),
	AMERICAN_BULLDOG("American Bulldog", "American%20Bulldog"),
	AMERICAN_ESKIMO_DOG("American Eskimo Dog", "American%20Eskimo%20Dog"),
	AMERICAN_HAIRLESS_TERRIER(
			"American Hairless Terrier",
			"American%20Hairless%20Terrier"),
	AMERICAN_STAFFORDSHIRE_TERRIER(
			"American Staffordshire Terrier",
			"American%20Staffordshire%20Terrier"),
	AMERICAN_WATER_SPANIEL(
			"American Water Spaniel",
			"American%20Water%20Spaniel"),
	ANATOLIAN_SHEPHERD("Anatolian Shepherd", "Anatolian%20Shepherd"),
	APPENZELL_MOUNTAIN_DOG(
			"Appenzell Mountain Dog",
			"Appenzell%20Mountain%20Dog"),
	AUSTRALIAN_CATTLE_DOG_BLUE_HEELER(
			"Australian Cattle Dog/Blue Heeler",
			"Australian%20Cattle%20Dog%20(Blue%20Heeler)"),
	AUSTRALIAN_KELPIE("Australian Kelpie", "Australian%20Kelpie"),
	AUSTRALIAN_SHEPHERD("Australian Shepherd", "Australian%20Shepherd"),
	AUSTRALIAN_TERRIER("Australian Terrier", "Australian%20Terrier"),
	BASENJI("Basenji", "Basenji"),
	BASSET_HOUND("Basset Hound", "Basset%20Hound"),
	BEAGLE("Beagle", "Beagle"),
	BEARDED_COLLIE("Bearded Collie", "Bearded%20Collie"),
	BEAUCERON("Beauceron", "Beauceron"),
	BEDLINGTON_TERRIER("Bedlington Terrier", "Bedlington%20Terrier"),
	BELGIAN_SHEPHERD_DOG_SHEEPDOG(
			"Belgian Shepherd Dog Sheepdog",
			"Belgian%20Shepherd%20Dog%20Sheepdog"),
	BELGIAN_SHEPHERD_LAEKENOIS(
			"Belgian Shepherd Laekenois",
			"Belgian%20Shepherd%20Laekenois"),
	BELGIAN_SHEPHERD_MALINOIS(
			"Belgian Shepherd Malinois",
			"Belgian%20Shepherd%20Malinois"),
	BELGIAN_SHEPHERD_TERVUREN(
			"Belgian Shepherd Tervuren",
			"Belgian%20Shepherd%20Tervuren"),
	BERNESE_MOUNTAIN_DOG("Bernese Mountain Dog", "Bernese%20Mountain%20Dog"),
	BICHON_FRISE("Bichon Frise", "Bichon%20Frise"),
	BLACK_AND_TAN_COONHOUND(
			"Black and Tan Coonhound",
			"Black%20and%20Tan%20Coonhound"),
	BLACK_LABRADOR_RETRIEVER(
			"Black Labrador Retriever",
			"Black%20Labrador%20Retriever"),
	BLACK_MOUTH_CUR("Black Mouth Cur", "Black%20Mouth%20Cur"),
	BLACK_RUSSIAN_TERRIER("Black Russian Terrier", "Black%20Russian%20Terrier"),
	BLOODHOUND("Bloodhound", "Bloodhound"),
	BLUE_LACY("Blue Lacy", "Blue%20Lacy"),
	BLUETICK_COONHOUND("Bluetick Coonhound", "Bluetick%20Coonhound"),
	BOERBOEL("Boerboel", "Boerboel"),
	BOLOGNESE("Bolognese", "Bolognese"),
	BORDER_COLLIE("Border Collie", "Border%20Collie"),
	BORDER_TERRIER("Border Terrier", "Border%20Terrier"),
	BORZOI("Borzoi", "Borzoi"),
	BOSTON_TERRIER("Boston Terrier", "Boston%20Terrier"),
	BOUVIER_DES_FLANDERS("Bouvier des Flanders", "Bouvier%20des%20Flanders"),
	BOXER("Boxer", "Boxer"),
	BOYKIN_SPANIEL("Boykin Spaniel", "Boykin%20Spaniel"),
	BRIARD("Briard", "Briard"),
	BRITTANY_SPANIEL("Brittany Spaniel", "Brittany%20Spaniel"),
	BRUSSELS_GRIFFON("Brussels Griffon", "Brussels%20Griffon"),
	BULL_TERRIER("Bull Terrier", "Bull%20Terrier"),
	BULLMASTIFF("Bullmastiff", "Bullmastiff"),
	CAIRN_TERRIER("Cairn Terrier", "Cairn%20Terrier"),
	CANAAN_DOG("Canaan Dog", "Canaan%20Dog"),
	CANE_CORSO_MASTIFF("Cane Corso Mastiff", "Cane%20Corso%20Mastiff"),
	CAROLINA_DOG("Carolina Dog", "Carolina%20Dog"),
	CATAHOULA_LEOPARD_DOG("Catahoula Leopard Dog", "Catahoula%20Leopard%20Dog"),
	CATTLE_DOG("Cattle Dog", "Cattle%20Dog"),
	CAUCASIAN_SHEEPDOG_CAUCASIAN_OVTCHARKA(
			"Caucasian Sheepdog (Caucasian Ovtcharka)",
			"Caucasian%20Sheepdog%20(Caucasian%20Ovtcharka)"),
	CAVALIER_KING_CHARLES_SPANIEL(
			"Cavalier King Charles Spaniel",
			"Cavalier%20King%20Charles%20Spaniel"),
	CHESAPEAKE_BAY_RETRIEVER(
			"Chesapeake Bay Retriever",
			"Chesapeake%20Bay%20Retriever"),
	CHIHUAHUA("Chihuahua", "Chihuahua"),
	CHINESE_CRESTED_DOG("Chinese Crested Dog", "Chinese%20Crested%20Dog"),
	CHINESE_FOO_DOG("Chinese Foo Dog", "Chinese%20Foo%20Dog"),
	CHINOOK("Chinook", "Chinook"),
	CHOCOLATE_LABRADOR_RETRIEVER(
			"Chocolate Labrador Retriever",
			"Chocolate%20Labrador%20Retriever"),
	CHOW_CHOW("Chow Chow", "Chow%20Chow"),
	CIRNECO_DELL_ETNA("Cirneco dell'Etna", "Cirneco%20Dell'etna"),
	CLUMBER_SPANIEL("Clumber Spaniel", "Clumber%20Spaniel"),
	COCKAPOO("Cockapoo", "Cockapoo"),
	COCKER_SPANIEL("Cocker Spaniel", "Cocker%20Spaniel"),
	COLLIE("Collie", "Collie"),
	COONHOUND("Coonhound", "Coonhound"),
	CORGI("Corgi", "Corgi"),
	COTON_DE_TULEAR("Coton de Tulear", "Coton%20de%20Tulear"),
	CURLY_COATED_RETRIEVER("Curly-Coated Retriever", "Curly-Coated%20Retriever"),
	DACHSHUND("Dachshund", "Dachshund"),
	DALMATIAN("Dalmatian", "Dalmatian"),
	DANDI_DINMONT_TERRIER("Dandi Dinmont Terrier", "Dandi%20Dinmont%20Terrier"),
	DOBERMAN_PINSCHER("Doberman Pinscher", "Doberman%20Pinscher"),
	DOGO_ARGENTINO("Dogo Argentino", "Dogo%20Argentino"),
	DOGUE_DE_BORDEAUX("Dogue de Bordeaux", "Dogue%20de%20Bordeaux"),
	DUTCH_SHEPHERD("Dutch Shepherd", "Dutch%20Shepherd"),
	ENGLISH_BULLDOG("English Bulldog", "English%20Bulldog"),
	ENGLISH_COCKER_SPANIEL(
			"English Cocker Spaniel",
			"English%20Cocker%20Spaniel"),
	ENGLISH_COONHOUND("English Coonhound", "English%20Coonhound"),
	ENGLISH_POINTER("English Pointer", "English%20Pointer"),
	ENGLISH_SETTER("English Setter", "English%20Setter"),
	ENGLISH_SHEPHERD("English Shepherd", "English%20Shepherd"),
	ENGLISH_SPRINGER_SPANIEL(
			"English Springer Spaniel",
			"English%20Springer%20Spaniel"),
	ENGLISH_TOY_SPANIEL("English Toy Spaniel", "English%20Toy%20Spaniel"),
	ENTLEBUCHER("Entlebucher", "Entlebucher"),
	ESKIMO_DOG("Eskimo Dog", "Eskimo%20Dog"),
	FEIST("Feist", "Feist"),
	FIELD_SPANIEL("Field Spaniel", "Field%20Spaniel"),
	FILA_BRASILEIRO("Fila Brasileiro", "Fila%20Brasileiro"),
	FINNISH_LAPPHUND("Finnish Lapphund", "Finnish%20Lapphund"),
	FINNISH_SPITZ("Finnish Spitz", "Finnish%20Spitz"),
	FLAT_COATED_RETRIEVER("Flat-coated Retriever", "Flat-coated%20Retriever"),
	FOX_TERRIER("Fox Terrier", "Fox%20Terrier"),
	FOXHOUND("Foxhound", "Foxhound"),
	FRENCH_BULLDOG("French Bulldog", "French%20Bulldog"),
	GALGO_SPANISH_GREYHOUND(
			"Galgo Spanish Greyhound",
			"Galgo%20Spanish%20Greyhound"),
	GERMAN_PINSCHER("German Pinscher", "German%20Pinscher"),
	GERMAN_SHEPHERD_DOG("German Shepherd Dog", "German%20Shepherd%20Dog"),
	GERMAN_SHORTHAIRED_POINTER(
			"German Shorthaired Pointer",
			"German%20Shorthaired%20Pointer"),
	GERMAN_SPITZ("German Spitz", "German%20Spitz"),
	GERMAN_WIREHAIRED_POINTER(
			"German Wirehaired Pointer",
			"German%20Wirehaired%20Pointer"),
	GIANT_SCHNAUZER("Giant Schnauzer", "Giant%20Schnauzer"),
	GLEN_OF_IMAAL_TERRIER(
			"Glen of Imaal Terrier",
			"Glen%20of%20Imaal%20Terrier"),
	GOLDEN_RETRIEVER("Golden Retriever", "Golden%20Retriever"),
	GORDON_SETTER("Gordon Setter", "Gordon%20Setter"),
	GREAT_DANE("Great Dane", "Great%20Dane"),
	GREAT_PYRENEES("Great Pyrenees", "Great%20Pyrenees"),
	GREATER_SWISS_MOUNTAIN_DOG(
			"Greater Swiss Mountain Dog",
			"Greater%20Swiss%20Mountain%20Dog"),
	GREYHOUND("Greyhound", "Greyhound"),
	HARRIER("Harrier", "Harrier"),
	HAVANESE("Havanese", "Havanese"),
	HOUND("Hound", "Hound"),
	HOVAWART("Hovawart", "Hovawart"),
	HUSKY("Husky", "Husky"),
	IBIZAN_HOUND("Ibizan Hound", "Ibizan%20Hound"),
	ILLYRIAN_SHEEPDOG("Illyrian Sheepdog", "Illyrian%20Sheepdog"),
	IRISH_SETTER("Irish Setter", "Irish%20Setter"),
	IRISH_TERRIER("Irish Terrier", "Irish%20Terrier"),
	IRISH_WATER_SPANIEL("Irish Water Spaniel", "Irish%20Water%20Spaniel"),
	IRISH_WOLFHOUND("Irish Wolfhound", "Irish%20Wolfhound"),
	ITALIAN_GREYHOUND("Italian Greyhound", "Italian%20Greyhound"),
	ITALIAN_SPINONE("Italian Spinone", "Italian%20Spinone"),
	JACK_RUSSELL_TERRIER("Jack Russell Terrier", "Jack%20Russell%20Terrier"),
	JACK_RUSSELL_TERRIER_PARSON_RUSSELL_TERRIER(
			"Jack Russell Terrier (Parson Russell Terrier)",
			"Jack%20Russell%20Terrier%20(Parson%20Russell%20Terrier)"),
	JAPANESE_CHIN("Japanese Chin", "Japanese%20Chin"),
	JINDO("Jindo", "Jindo"),
	KAI_DOG("Kai Dog", "Kai%20Dog"),
	KARELIAN_BEAR_DOG("Karelian Bear Dog", "Karelian%20Bear%20Dog"),
	KEESHOND("Keeshond", "Keeshond"),
	KERRY_BLUE_TERRIER("Kerry Blue Terrier", "Kerry%20Blue%20Terrier"),
	KISHU("Kishu", "Kishu"),
	KLEE_KAI("Klee Kai", "Klee%20Kai"),
	KOMONDOR("Komondor", "Komondor"),
	KUVASZ("Kuvasz", "Kuvasz"),
	KYI_LEO("Kyi Leo", "Kyi%20Leo"),
	LABRADOR_RETRIEVER("Labrador Retriever", "Labrador%20Retriever"),
	LAKELAND_TERRIER("Lakeland Terrier", "Lakeland%20Terrier"),
	LANCASHIRE_HEELER("Lancashire Heeler", "Lancashire%20Heeler"),
	LEONBERGER("Leonberger", "Leonberger"),
	LHASA_APSO("Lhasa Apso", "Lhasa%20Apso"),
	LOWCHEN("Lowchen", "Lowchen"),
	MALTESE("Maltese", "Maltese"),
	MANCHESTER_TERRIER("Manchester Terrier", "Manchester%20Terrier"),
	MAREMMA_SHEEPDOG("Maremma Sheepdog", "Maremma%20Sheepdog"),
	MASTIFF("Mastiff", "Mastiff"),
	MCNAB("McNab", "McNab"),
	MINIATURE_PINSCHER("Miniature Pinscher", "Miniature%20Pinscher"),
	MOUNTAIN_CUR("Mountain Cur", "Mountain%20Cur"),
	MOUNTAIN_DOG("Mountain Dog", "Mountain%20Dog"),
	MUNSTERLANDER("Munsterlander", "Munsterlander"),
	NEAPOLITAN_MASTIFF("Neapolitan Mastiff", "Neapolitan%20Mastiff"),
	NEW_GUINEA_SINGING_DOG(
			"New Guinea Singing Dog",
			"New%20Guinea%20Singing%20Dog"),
	NEWFOUNDLAND_DOG("Newfoundland Dog", "Newfoundland%20Dog"),
	NORFOLK_TERRIER("Norfolk Terrier", "Norfolk%20Terrier"),
	NORWEGIAN_BUHUND("Norwegian Buhund", "Norwegian%20Buhund"),
	NORWEGIAN_ELKHOUND("Norwegian Elkhound", "Norwegian%20Elkhound"),
	NORWEGIAN_LUNDEHUND("Norwegian Lundehund", "Norwegian%20Lundehund"),
	NORWICH_TERRIER("Norwich Terrier", "Norwich%20Terrier"),
	NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER(
			"Nova Scotia Duck-Tolling Retriever",
			"Nova%20Scotia%20Duck-Tolling%20Retriever"),
	OLD_ENGLISH_SHEEPDOG("Old English Sheepdog", "Old%20English%20Sheepdog"),
	OTTERHOUND("Otterhound", "Otterhound"),
	PAPILLON("Papillon", "Papillon"),
	PATTERDALE_TERRIER_FELL_TERRIER(
			"Patterdale Terrier (Fell Terrier)",
			"Patterdale%20Terrier%20(Fell%20Terrier)"),
	PEKINGESE("Pekingese", "Pekingese"),
	PERUVIAN_INCA_ORCHID("Peruvian Inca Orchid", "Peruvian%20Inca%20Orchid"),
	PETIT_BASSET_GRIFFON_VENDEEN(
			"Petit Basset Griffon Vendeen",
			"Petit%20Basset%20Griffon%20Vendeen"),
	PHARAOH_HOUND("Pharaoh Hound", "Pharaoh%20Hound"),
	PIT_BULL_TERRIER("Pit Bull Terrier", "Pit%20Bull%20Terrier"),
	PLOTT_HOUND("Plott Hound", "Plott%20Hound"),
	PODENGO_PORTUGUESO("Podengo Portugueso", "Podengo%20Portugueso"),
	POINTER("Pointer", "Pointer"),
	POLISH_LOWLAND_SHEEPDOG(
			"Polish Lowland Sheepdog",
			"Polish%20Lowland%20Sheepdog"),
	POMERANIAN("Pomeranian", "Pomeranian"),
	POODLE("Poodle", "Poodle"),
	PORTUGUESE_WATER_DOG("Portuguese Water Dog", "Portuguese%20Water%20Dog"),
	PRESA_CANARIO("Presa Canario", "Presa%20Canario"),
	PUG("Pug", "Pug"),
	PULI("Puli", "Puli"),
	PUMI("Pumi", "Pumi"),
	RAT_TERRIER("Rat Terrier", "Rat%20Terrier"),
	REDBONE_COONHOUND("Redbone Coonhound", "Redbone%20Coonhound"),
	RETRIEVER("Retriever", "Retriever"),
	RHODESIAN_RIDGEBACK("Rhodesian Ridgeback", "Rhodesian%20Ridgeback"),
	ROTTWEILER("Rottweiler", "Rottweiler"),
	SAINT_BERNARD_ST_BERNARD(
			"Saint Bernard St. Bernard",
			"Saint%20Bernard%20St.%20Bernard"),
	SALUKI("Saluki", "Saluki"),
	SAMOYED("Samoyed", "Samoyed"),
	SARPLANINAC("Sarplaninac", "Sarplaninac"),
	SCHIPPERKE("Schipperke", "Schipperke"),
	SCHNAUZER("Schnauzer", "Schnauzer"),
	SCOTTISH_DEERHOUND("Scottish Deerhound", "Scottish%20Deerhound"),
	SCOTTISH_TERRIER_SCOTTIE(
			"Scottish Terrier Scottie",
			"Scottish%20Terrier%20Scottie"),
	SEALYHAM_TERRIER("Sealyham Terrier", "Sealyham%20Terrier"),
	SETTER("Setter", "Setter"),
	SHAR_PEI("Shar Pei", "Shar%20Pei"),
	SHEEP_DOG("Sheep Dog", "Sheep%20Dog"),
	SHEPHERD("Shepherd", "Shepherd"),
	SHETLAND_SHEEPDOG_SHELTIE(
			"Shetland Sheepdog Sheltie",
			"Shetland%20Sheepdog%20Sheltie"),
	SHIBA_INU("Shiba Inu", "Shiba%20Inu"),
	SHIH_TZU("Shih Tzu", "Shih%20Tzu"),
	SIBERIAN_HUSKY("Siberian Husky", "Siberian%20Husky"),
	SILKY_TERRIER("Silky Terrier", "Silky%20Terrier"),
	SKYE_TERRIER("Skye Terrier", "Skye%20Terrier"),
	SLOUGHI("Sloughi", "Sloughi"),
	SMOOTH_FOX_TERRIER("Smooth Fox Terrier", "Smooth%20Fox%20Terrier"),
	SOUTH_RUSSIAN_OVTCHARKA(
			"South Russian Ovtcharka",
			"South%20Russian%20Ovtcharka"),
	SPANIEL("Spaniel", "Spaniel"),
	SPITZ("Spitz", "Spitz"),
	STAFFORDSHIRE_BULL_TERRIER(
			"Staffordshire Bull Terrier",
			"Staffordshire%20Bull%20Terrier"),
	STANDARD_POODLE("Standard Poodle", "Standard%20Poodle"),
	SUSSEX_SPANIEL("Sussex Spaniel", "Sussex%20Spaniel"),
	SWEDISH_VALLHUND("Swedish Vallhund", "Swedish%20Vallhund"),
	TERRIER("Terrier", "Terrier"),
	THAI_RIDGEBACK("Thai Ridgeback", "Thai%20Ridgeback"),
	TIBETAN_MASTIFF("Tibetan Mastiff", "Tibetan%20Mastiff"),
	TIBETAN_SPANIEL("Tibetan Spaniel", "Tibetan%20Spaniel"),
	TIBETAN_TERRIER("Tibetan Terrier", "Tibetan%20Terrier"),
	TOSA_INU("Tosa Inu", "Tosa%20Inu"),
	TOY_FOX_TERRIER("Toy Fox Terrier", "Toy%20Fox%20Terrier"),
	TREEING_WALKER_COONHOUND(
			"Treeing Walker Coonhound",
			"Treeing%20Walker%20Coonhound"),
	VIZSLA("Vizsla", "Vizsla"),
	WEIMARANER("Weimaraner", "Weimaraner"),
	WELSH_CORGI("Welsh Corgi", "Welsh%20Corgi"),
	WELSH_SPRINGER_SPANIEL(
			"Welsh Springer Spaniel",
			"Welsh%20Springer%20Spaniel"),
	WELSH_TERRIER("Welsh Terrier", "Welsh%20Terrier"),
	WEST_HIGHLAND_WHITE_TERRIER_WESTIE(
			"West Highland White Terrier Westie",
			"West%20Highland%20White%20Terrier%20Westie"),
	WHEATEN_TERRIER("Wheaten Terrier", "Wheaten%20Terrier"),
	WHIPPET("Whippet", "Whippet"),
	WHITE_GERMAN_SHEPHERD("White German Shepherd", "White%20German%20Shepherd"),
	WIRE_FOX_TERRIER("Wire Fox Terrier", "Wire%20Fox%20Terrier"),
	WIRE_HAIRED_POINTING_GRIFFON(
			"Wire-haired Pointing Griffon",
			"Wire-haired%20Pointing%20Griffon"),
	WIREHAIRED_TERRIER("Wirehaired Terrier", "Wirehaired%20Terrier"),
	XOLOITZCUINTLE_MEXICAN_HAIRLESS(
			"Xoloitzcuintle/Mexican Hairless",
			"Xoloitzcuintle%20(Mexican%20Hairless)"),
	YELLOW_LABRADOR_RETRIEVER(
			"Yellow Labrador Retriever",
			"Yellow%20Labrador%20Retriever"),
	YORKSHIRE_TERRIER_YORKIE(
			"Yorkshire Terrier Yorkie",
			"Yorkshire%20Terrier%20Yorkie");

	String name;
	String value;

	DogType(String name, String value) {
		this.name = name;
		this.value = value;
	}

	@Override
	public String toString() {
		return this.name;
	}

	public String getName() {
		return this.name;
	}

	public String getValue() {
		return this.value;
	}
}
